### ISSUE TITLE
some problems always occur when I import hotel-api-sdk-java project to eclipse.

### ISSUE THREAD

**Issue by mpaster** [hotelbeds-sdk/hotel-api-sdk-java#1]
i cant't find variable 'log',like:
if (!result) {
        log.info("Date is not valid, it is not in the future, date: " + date);
 }
including other source file.
and also cant find some methods in availabilityRQ, like here:
if (availabilityRQ.getDestination() != null) {
            found = found + 1;
        }
could u tell me how to get it .thanks !

**Comment by Verdoso** [comment]
Hi there,
In order to avoid most boilerplate code, we are using [Lombok](https://projectlombok.org/) to develop the SDK and related libraries, so if you want to build the SDK yourself, you have to install it as well. Don't worry, it's fairly easy. You can find a tutorial with installation instructions [here](http://jnb.ociweb.com/jnb/jnbJan2010.html).

Once you have it installed, Eclipse will recognise the log variable (It's added thanks to the Slf4j annotation) and it will also detect the generated getters/setters etc.

Cheers!
D.

**Comment by Verdoso** [comment]
On a related note, you don't need to build the SDK from source unless you want to. If all you want is to access the API, you can simply import the SDK into your project through whatever method you choose (Maven, Gradle, by hand...). Lombok is not required at runtime.

**Comment by mpaster** [comment]
where can I download the SDK jar that can be imported directly to my project?

**Comment by Verdoso** [comment]
You can find some instructions for Maven in the project [README](https://github.com/hotelbeds-sdk/hotel-api-sdk-java/blob/master/README.md#getting-the-sdk).

We strongly recommend using some kind of dependency management to download the SDK, as otherwise you'll also need to download the required dependencies one by one.

**Comment by mpaster** [comment]
First of all, thank you very much for your answers so patiently for me yesterday, but I still can't understand  how to use the SDK because I'm very new in java world, so, can you explain to me in great detail how to use again?Such as, I don't know how to use dependency management to download the SDK.Thanks again!

**Comment by Verdoso** [comment]
Hi,
If you are new to the Java world, you have quite a road ahead ;), but here you have a headstart to play with the SDK:

.- Follow the "[Maven in 5 Minutes](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html)" instructions to install Maven and play a bit with it. 
.- As instructed in that tutorial, execute the following line to create a sample project
mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false

.- Then edit my-app\pom.xml and make it look like this one. See that I added the repository where to get the SDK, the SDK as dependency and the maven-assembly-plugin to create an executable jar so you don't have to add the dependencies to the classpath one by one in the command line.
--------- my-app\pom.xml ----------
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>my-app</name>
  <url>http://maven.apache.org</url>
  <repositories>
      <repository>
          <id>ossrh</id>
          <url>https://oss.sonatype.org/content/groups/staging</url>
      </repository>
  </repositories>
  <dependencies>
    <dependency>
      <groupId>com.hotelbeds.hotel-api-sdk-java</groupId>
      <artifactId>hotel-api-sdk</artifactId>
      <version>0.6-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>2.6</version>
        <configuration>
          <appendAssemblyId>false</appendAssemblyId>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
          <archive>
            <manifest>
              <mainClass>com.mycompany.app.App</mainClass>
            </manifest>
          </archive>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
----------------

Then edit the sample application that was created in the project (my-app\src\main\java\com\mycompany\app\App.java) and make it look like this one:
-------- my-app\src\main\java\com\mycompany\app\App.java --------
package com.mycompany.app;

import java.time.LocalDate;

import com.hotelbeds.distribution.hotel_api_model.auto.messages.AvailabilityRS;
import com.hotelbeds.distribution.hotel_api_model.auto.model.Hotel;
import com.hotelbeds.distribution.hotel_api_model.auto.model.Rate;
import com.hotelbeds.distribution.hotel_api_model.auto.model.Room;
import com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient;
import com.hotelbeds.distribution.hotel_api_sdk.helpers.AvailRoom;
import com.hotelbeds.distribution.hotel_api_sdk.helpers.Availability;
import com.hotelbeds.distribution.hotel_api_sdk.types.HotelSDKException;

/**
 * Sample usage of the SDK
 *
 */
public class App {
    public static void main(String[] args) throws HotelSDKException {
        HotelApiClient apiClient = new HotelApiClient();
        apiClient.setReadTimeout(40000);
        apiClient.init();
        // @formatter:off
        AvailabilityRS availabilityRS =
            apiClient.availability(
                Availability.builder()
                .language("ENG")
                .checkIn(LocalDate.now().plusDays(30))
                .checkOut(LocalDate.now().plusDays(32))
                .addRoom(AvailRoom.builder().adults(2).children(1).childOf(4))
                .destination("LON")
                .build()
            );
        if (availabilityRS != null && availabilityRS.getHotels() != null && availabilityRS.getHotels().getHotels() != null) {
            for(Hotel hotel : availabilityRS.getHotels().getHotels())
            {
                System.err.println("Hotel: " + hotel.getName());
                for(Room room : hotel.getRooms())
                {
                    for(Rate rate: room.getRates()) {
                        System.err.println("Room/rate " + room.getCode() + " - " + room.getName() + " / " + rate.getBoardName() + "(" + rate.getNet() + hotel.getCurrency() + ")");
                    }
                }
                System.err.println("-------------------------------");
            }
        }
        else
        {
            System.err.println("No availability");
        }
        // @formatter:on
    }
}
----------------

Then create the directory my-app\src\main\resources and add a file there (hotelapi.properties) so it ends like this:
----- my-app\src\main\resources\hotelapi.properties -----------
hotelapi.apikey=**YOUR*API*KEY*HERE**
hotelapi.sharedsecret=**YOUR*SHARED*SECRET*HERE**
hotelapi.service=TEST
----------------
**YOUR*API*KEY*HERE** and **YOUR*SHARED*SECRET*HERE** have to be replaced with the data that you must have from the registration at https://developer.hotelbeds.com/

You can then go to the my-app directory.
cd my-app
Package the whole project (it will compile the source and create a .jar file with everything required inside)
mvn package
And then execute it
java -jar target\my-app-1.0-SNAPSHOT.jar

The sample code checks the availabily in London of a room for 2 days for 2 adults and a child of 4, starting in 30 days. So you should see some results.

After that, I would recommend getting deeper in the Java world so you have more experience to solve the issues that will come up. We have made the SDK as simple to use as possible, but it still requires one to be quite familiar with the Java world. There are core concepts like the classpath, using libraries, exceptions etc. that once you are familiar with, they are not such a big deal, but until then, they can make even the simplest problem look bigger :).

I hope that at least with this you can see some of what lies beneath.
Cheers,

**Comment by mpaster** [comment]
I am very happy that I succeed finally with your help. Thank you very much :).

**Comment by Verdoso** [comment]
Good to hear.

Happy coding!
