### ISSUE TITLE
problem with AVAILABILITY method

### ISSUE THREAD

**Issue by followme109** [hotelbeds-sdk/hotel-api-sdk-java#10]
Hi,
When I try to call availability(..) method with your SDK for Java (0.6 stable version) I recieve this response:

```
HotelSDKException(error=HotelbedsError(code=org.springframework.http.converter.HttpMessageNotReadableException,
message=Could not read document: Can not instantiate value of type [simple type, class java.time.LocalDate] from String value ('2016-09-01');
no single-String constructor/factory method
at [Source: java.io.ByteArrayInputStream@7701096a; line: 1, column: 1052844] (through reference chain: com.hotelbeds.distribution.hotel_api_model.auto.messages.AvailabilityRS["hotels"]->com.hotelbeds.distribution.hotel_api_model.auto.model.Hotels["checkIn"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class java.time.LocalDate] from String value ('2016-09-01'); no single-String constructor/factory method
at [Source: java.io.ByteArrayInputStream@7701096a; line: 1, column: 1052844] (through reference chain: com.hotelbeds.distribution.hotel_api_model.auto.messages.AvailabilityRS["hotels"]->com.hotelbeds.distribution.hotel_api_model.auto.model.Hotels["checkIn"])))
```

In the AvailabilityRS object I set the checkin date also in this mode to be sure to create a correct LocalDate to test this method: checkIn(LocalDate.of(2016, Month.SEPTEMBER, 1))

Can you help me?

Thanks and best regards,
Giorgio Romerio

**Comment by alvmunoz** [comment]
Does the demo work for you?
Can you copy here your code so we can find what's wrong?  
Thanks,

**Comment by Verdoso** [comment]
That unmarshalling should be handled automatically by Jackson, simply by having jackson-datatype-jsr310.jar in the classpath. Make sure you have that library (it's a dependency of the SDK and it should have been downloaded with it when building the project).

You might also want to try with SDK 0.8-SNAPSHOT and see if that version works for you, just to discard version-specific issues.
Cheers

**Comment by followme109** [comment]
I've the library you mentioned inside the 0.6 version, but it doesn't work.

![print1](https://cloud.githubusercontent.com/assets/19840796/15965863/9bd7cac6-2f20-11e6-815c-ad1e2db1e59e.png)

```
availability = Availability.builder()
                    .language(rq.getLanguageCode())
                    .destination(hotelsCodeOrDestinations)
//                    .checkIn(rq.getStartDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate())
                    .checkIn(LocalDate.of(2016, Month.SEPTEMBER, 1))
//                    .checkOut(rq.getEndDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate())
                    .checkOut(LocalDate.of(2016, Month.SEPTEMBER, 4))
                    .rooms(rooms)
                    .build();
```

The commented row are the original, but just to check the behavior of your SDK I instantiate 2 LocalDates.
Hope to be clear.

Thanks,
Giorgio

**Comment by alvmunoz** [comment]
Hi,
can you update to version 0.8 SNAPSHOT and let us know if that fixes the issue? 

I guess you receive the same error with the original rows??

**Comment by Verdoso** [comment]
Hi followme109,
Did you try with the 0.8-SNAPSHOT version?

**Comment by vmavromatis** [comment]
@followme109, I will be closing the issue. If you have any more questions/issues feel free to re-open.
