### ISSUE TITLE
missing totalNet() currency() in cancel and booking response

### ISSUE THREAD

**Issue by followme109** [hotelbeds-sdk/hotel-api-sdk-java#11]
Hi,
in the object BookingRS/Booking inside the response of Booking() I can't find TOTALNET e CURRENCY getter methods.
The same missing for the object bookingCancellationRS/Booking inside the response of the Cancel().

Can you fix it?
thanks and Best Regards,

Giorgio Romerio

**Comment by alvmunoz** [comment]
Hi,

I can see the getTotalNet() and getCurrency() methods. 

Attach screenshot. 

![image](https://cloud.githubusercontent.com/assets/17126683/15957452/abeef5a0-2eef-11e6-8b12-65f94a18f6b7.png)

Is that what you mean?

**Comment by followme109** [comment]
Yes, but as you can see below I don't have that method.. I use the 0.6 version (documentation indicate is the stable one).

![print](https://cloud.githubusercontent.com/assets/19840796/15965214/d0cfcd90-2f1c-11e6-9149-b9efa271ac33.png)

**Comment by alvmunoz** [comment]
@followme109 , version 0.8 is RC.  We will be releasing it soon. 
Can you use the 0.8 SNAPSHOT and try again?

**Comment by vmavromatis** [comment]
@followme109, I will be closing the issue. If you have any more questions/issues feel free to re-open.
