### ISSUE TITLE
doCheckRate(...) -> request is not compliant with the specified version of the API

### ISSUE THREAD

**Issue by followme109** [hotelbeds-sdk/hotel-api-sdk-java#12]
Hi,
when I try to call apiClient.doCheckRate(..) of SDK 0.6 with this rate_key: 2643|STU.C2|REP-OPACO|1|FB||1~1~1|8|20160901|20160904|W|N#236920111
(found in the documentation and adapt with a new date), I recieve this response:

`HotelSDKException(error=HotelbedsError(code=INVALID_REQUEST-EED0FD5DF4F0452D92D994B820092EFF, message=The request is not compliant with the specified version of the API. Error at property rooms->rateKey: Index: 1, Size: 1))`

can you help me? or can you provide me a valid rate_key to test the checkRate and the booking calls?
I still can't perform an availability() call to have a valid rate_key because of precedent issue still open for me.

Thanks,
Giorgio

**Comment by alvmunoz** [comment]
I can provide you an apikey: 
20160615|20160620|W|52|1|DBT.ST|CG-VARIOS|RO||1~2~0||N@-1413947864 

This is for 2 adults and 1 room.

However if you don't use it within 30 minutes it will expire.

**Comment by vmavromatis** [comment]
@followme109, I will be closing the issue. If you have any more questions/issues feel free to re-open.
