### ISSUE TITLE
hotel-content-model

### ISSUE THREAD

**Issue by bcharli** [hotelbeds-sdk/hotel-api-sdk-java#13]
Could you provide a sample code how to use hotel-content-model?
This sample code for hotel-api-model is very useful. I need to get images path for a hotel but can't find how to do that.

Thanks in advance.

**Comment by Verdoso** [comment]
Hi,
There is also some sample code regarding the use of the hotel-content side of the SDK, even though it is not yet as complete. You can see it here: [HotelContentSample.java](https://github.com/hotelbeds-sdk/hotel-api-sdk-java/blob/master/hotel-api-sdk-demo/src/main/java/com/hotelbeds/demo/simple/HotelContentSample.java).

In your case, it would be as simple as this test...
`
import com.hotelbeds.hotelcontentapi.auto.messages.Hotel;
import com.hotelbeds.hotelcontentapi.auto.messages.Image;
...
// You already know how to instance an HotelApiCilent, huh?
...
final int hotelCode = ...
final String language = ...;
Hotel hotel = hotelApiClient.getHotel(hotelCode, language, false);
if (hotel.getImages() != null) {
	for (Image image : hotel.getImages()) {
		log.info("hotel: Room {}-{} Path: {}", new Object[] {
			hotel.getCode(), image.getRoomCode(), image.getRoomType(), image.getPath()});
	}
}
`
Note however, that depending on your ApiKeys settings, using the HotelContent API might throw a:
HotelApiSDKException(error=HotelbedsError(code=Invalid response, message=Wrong content typetext/xml))
that it really means that you went over your quota of calls for that developers' key. 

That message should be improved, and I'll open a ticket about it, right now ;)

**Comment by bcharli** [comment]
Thanks for fast response.

It doesn't look like I exceeded quota:

2016-07-01 08:27:35 DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: X-Application-Context: "hotelcontent:int,ignite:8080"
2016-07-01 08:27:35 DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: X-Mashery-Responder: "prod-j-worker-eu-west-1b-60.mashery.com"
2016-07-01 08:27:35 DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: X-Plan-QPS-Allotted: "4"
2016-07-01 08:27:35 DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: X-Plan-QPS-Current: "1"
2016-07-01 08:27:35 DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: X-Plan-Quota-Allotted: "500000"
2016-07-01 08:27:35 DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: X-Plan-Quota-Current: "7"
2016-07-01 08:27:35 DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: X-Plan-Quota-Reset: "Saturday, July 2, 2016 12:00:00 AM GMT"

But it looks like other internal error:

2016-07-01 08:27:35 ERROR com.example.RequestingAvailability - Error requesting availability
com.hotelbeds.distribution.hotel_api_sdk.types.HotelApiSDKException: HotelSDKException (Error SYSTEM_ERROR-F112F7AB021E44BE81659316C77139EF while performing operation
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteContentAPI(HotelApiClient.java:756)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.getHotel(HotelApiClient.java:422)
	at com.example.RequestingAvailability.findHotel(RequestingAvailability.java:80)
	at com.example.EffectiveVacationApplication.main(EffectiveVacationApplication.java:63)

**Comment by Verdoso** [comment]
Hi bcharli,
You closed the issue, did you already solve it? Looking at the timeline, you might have hit "comment and close" instead of simply comment. Silly GitHub UI :D.
If you are using the same code as the one I showed... which hotel are you trying to see and in which language? It is a simple operation, so it might be an issue handling that specific piece of data.

Also, if you set the log level of LoggingRequestInterceptor to TRACE you'll be able to see also the body of the request and the response, if you can copy them here, we should be able to pinpoint the issue quickly.

And lastly, is that against TEST or LIVE?

**Comment by bcharli** [comment]
I closed it by mistake and than I resolved that problem. I was using language "Eng" instead of "ENG"
For a while I've got this returning images path but now every image is null. It looks like something has change on your site just about yesterday evening.

I'm running it in a test mode.

I'm calling apiClient this way:

apiClient.getHotel(413080,"ENG",false).getImages()

Here is log in a trace mode.
Body:{"auditData":{"processTime":"6","timestamp":"2016-07-02 19:13:33.174","requestHost":"212.170.239.6","serverId":"sa3RKSJACHXE79K.env","environment":"[int, ignite]","release":"de32d4e38237a19a3e2ce91edaae6f1c1a63c41a"},"hotel":{"code":413080,"name":{"content":"Stergia 1"},"country":{"code":"GR","isoCode":"GR","description":{"content":"GREECE  "}},"destination":{"code":"KSS","name":{"content":"Kos"},"countryCode":"GR"},"zone":{"zoneCode":3,"name":"Kardamena","description":{"content":"Kardamena"}},"coordinates":{"longitude":27.14352269999995,"latitude":36.7822585},"category":{"code":"3LL","description":{"content":"3 KEYS"}},"categoryGroup":{"code":"GRUPO7","description":{"content":"Includes campings, apartments and aparthotels"}},"accommodationType":{"code":"APART","typeMultiDescription":{"content":"Apartment"},"typeDescription":"Apto"},"boards":[{"code":"SC","description":{"content":"SELF CATERING"}},{"code":"BB","description":{"content":"BED AND BREAKFAST"}}],"address":{"content":"KARDAMENA,  "},"postalCode":"85302","city":{"content":"KOS"},"email":"theo-mikos@hotmail.com","phones":[{"phoneNumber":"00302242091993","phoneType":"PHONEHOTEL"},{"phoneNumber":"00302242091993","phoneType":"FAXNUMBER"}],"rooms":[{"roomCode":"STU.C2","description":"STUDIO CAPACITY 2","type":{"code":"STU","description":{"content":"STUDIO"}},"characteristic":{"code":"C2","description":{"content":"CAPACITY 2"}}},{"roomCode":"APT.ST","description":"APARTMENT STANDARD","type":{"code":"APT","description":{"content":"APARTMENT"}},"characteristic":{"code":"ST","description":{"content":"STANDARD"}}},{"roomCode":"STU.C3","description":"STUDIO CAPACITY 3","type":{"code":"STU","description":{"content":"STUDIO"}},"characteristic":{"code":"C3","description":{"content":"CAPACITY 3"}}}]}}

**Comment by Verdoso** [comment]
Glad to know you got it working. Ummm, Eng is not a valid language, right, but it shouldn't be throwing an internal error back at you, thanks for reporting it. I'll open a ticket about it.

Regarding the images, I was checking also through the portal and it seems the hotel images in the testing DB are missing. That's probably just an issue with the periodic refreshing of the DB.
I'll check on monday to see what might have happened, but your code seems to be fiine, so as soon as we get the images back, you'll be able to get them.

Again, thanks for your feedback,
D.

**Comment by alvmunoz** [comment]
Yes, I confirm the images are missing in the test server. Will work on it.

**Comment by Verdoso** [comment]
I have restored the images, so you can try now and let us know if it works?
Thanks for your patience,
D.

**Comment by vmavromatis** [comment]
@bcharli I will be closing the issue now. Feel free to re-open if you have any concerns regarding the content model.
