### ISSUE TITLE
Exception in thread "main" HotelApiSDKException(error=HotelbedsError(code=INVALID_DATA-5f21d813-16ca-4e9e-a7b5-7619720d73f6, message=Invalid data. Destination search is not available by default. Please contact with API Distribution Team))

### ISSUE THREAD

**Issue by cristiangodoyy** [hotelbeds-sdk/hotel-api-sdk-java#18]
When I try to build a type AvailabilityRS get the following error message "Destination search is not available by default. Please Contact with API Distribution Team".
From time to time it stopped working construction Availability.builder ().

HotelApiClient apiClient = new HotelApiClient(
                HotelApiVersion.DEFAULT
                , HotelApiService.TEST
                , apiKey
                , sharedSecret );

```
    apiClient.setReadTimeout(40000);
    apiClient.init();

    AvailabilityRS availabilityRS =
            apiClient.availability(
                Availability.builder()
                .language("ENG")
                .checkIn(LocalDate.now().plusDays(5))
                .checkOut(LocalDate.now().plusDays(8))
                .addRoom(AvailRoom.builder().adults(1).children(1).childOf(4))
                .addRoom(AvailRoom.builder().adults(1))
                .destination("LON")
                .build()
            );
```

20161012 18:26:45 INFO -  - LoggingRequestInterceptor - Request: HTTP/1.1 POST https://api.test.hotelbeds.com/hotel-api/1.0/hotels, body:245 bytes
20161012 18:26:55 INFO -  - LoggingRequestInterceptor - Response: 400 Bad Request
20161012 18:26:55 INFO -  - LoggingRequestInterceptor -   Request took 10410 ms
Exception in thread "main" HotelApiSDKException(error=HotelbedsError(code=INVALID_DATA-5f21d813-16ca-4e9e-a7b5-7619720d73f6, message=Invalid data. Destination search is not available by default. Please contact with API Distribution Team))
    at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteAPI(HotelApiClient.java:697)
    at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteAPI(HotelApiClient.java:658)
    at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.doAvailability(HotelApiClient.java:309)
    at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.availability(HotelApiClient.java:303)
    at com.system.bol.hotelbeds.test.AppBol.main(AppBol.java:41)

**Comment by alvmunoz** [comment]
Hi @cristiangodoyy ,

As the error message stands,  you **cannot** use destination search by default, unless we enable it for you. 

Hence, you should change the                 .destination("LON")  line code and instead change it by a Hotel code search or a geolocation search.

Regards,

**Comment by cristiangodoyy** [comment]
@alvmunoz thanks for your time;
Another question:
As I can enable search the default destination?

**Comment by alvmunoz** [comment]
If you need to change your account settings please contact apitude@hotelbeds.com

**Comment by vmavromatis** [comment]
Hi @cristiangodoyy,
I will be closing this issue as it appears to be resolved. 

In the future, kindly use this space only to refer to SDK issues. For all API issues please refer to apitude@hotelbeds.com.
