### ISSUE TITLE
about GZIP

### ISSUE THREAD

**Issue by chen09** [hotelbeds-sdk/hotel-api-sdk-java#20]
Hotelbeds tech team emailed us that requests we sent have not been gziped. How to turn on GZIP? Thanks

**Comment by alvmunoz** [comment]
Hi @chen09 , are you using our Java SDK?  If you are using the last version it uses GZIP by default.

**Comment by vmavromatis** [comment]
Hi @chen09, 

to add to @alvmunoz's response, our latest version is 0.13. Make sure this is in your `pom.xml` file:

```
<dependency>
  <groupId>com.hotelbeds.hotel-api-sdk-java</groupId>
  <artifactId>hotel-api-sdk</artifactId>
  <version>0.13-SNAPSHOT</version>
</dependency>
```

I will be closing this issue, feel free to re-open it if you need any assistance.

**Comment by ishara** [comment]
Hi Team
How did this work ? where can I find the custom Interceptor for gzip?

Thanks
