### ISSUE TITLE
Error requesting availability HotelApiSDKException(error=HotelbedsError(code=Invalid response, message=Wrong content typetext/xml))

### ISSUE THREAD

**Issue by cristiangodoyy** [hotelbeds-sdk/hotel-api-sdk-java#22]
Hi @alvmunoz;
When I try an availability search I find the following error:

20170114 11:32:35 INFO - - LoggingRequestInterceptor - Request: HTTP / 1.1 POST https://api.test.hotelbeds.com/hotel-api/1.0/hotels, body: 216 bytes
20170114 11:32:37 INFO - - LoggingRequestInterceptor - Response: 403 Forbidden
20170114 11:32:37 INFO - - LoggingRequestInterceptor - Content-Length: 28
20170114 11:32:37 INFO - - LoggingRequestInterceptor - Request took 2618 ms
Exception in thread "main" HotelApiSDKException (error = HotelbedsError (code = Invalid response, message = Wrong content typetext / xml))

Here is my code:
HotelApiClient apiClient = new HotelApiClient (
HotelApiVersion.DEFAULT
                , HotelApiService.TEST
                , ApiKey
                , SharedSecret);

ApiClient.setReadTimeout (40000);
        ApiClient.init ();

AvailabilityRS availabilityRS =
ApiClient.availability (
Availability.builder ()
.matchingAnyKeyword ()
.language ("ENG")
.checkIn (LocalDate.now (). PlusDays (5))
.checkOut (LocalDate.now (). PlusDays (8))
.addRoom (AvailRoom.builder (). Adults (1) .children (1) .childOf (4))
.addRoom (AvailRoom.builder (). Adults (1))
 .destination ("LON") // you have to enable the search by default.
 .includeHotel (111637)
 .includeHotel (2818)
 .includeHotel (138465)
 .includeHotel (164471)
.build ()
);

**Comment by egotsev** [comment]
Hi, I ran into this as well. Turns out that the problem is already fixed - you can change the version of the SDK to 0.10-SNAPSHOT or 0.11-SNAPSHOT.

However, these versions are not listed in the README.md so I'm not sure if they are reliable and if they are going to be present long in the artifactory repo.

**Comment by alvmunoz** [comment]
@egotsev   ,  yes, these versions are reliable.  
@cristiangodoyy the problems relies on the fact that you cannot search by destination and by hotel at the same time:
.destination ("LON") 
.includeHotel (111637)

@Verdoso or @jrossello  , can you update the Readme.md to include the last version of the SNAPSHOT? 
Thanks.

**Comment by vmavromatis** [comment]
@alvmunoz updated latest SNAPSHOT and included in readme with aec98dc3c6113366e7465fbb1ccc50b9de46b879
