### ISSUE TITLE
Error when requesting Hotel Content (Date format Exception)

### ISSUE THREAD

**Issue by chriszhangz** [hotelbeds-sdk/hotel-api-sdk-java#23]
Here is the log when I get all destination:
20170213 11:55:14 INFO -  - LoggingRequestInterceptor - Request: HTTP/1.1 GET https://api.hotelbeds.com/hotel-content-api/1.0/locations/destinations?fields=all&language=ENG&useSecondaryLanguage=false&codes=&from=1&to=1000&lastUpdateTime=&countryCodes=
20170213 11:55:16 INFO -  - LoggingRequestInterceptor - Response: 400 Bad Request
20170213 11:55:16 INFO -  - LoggingRequestInterceptor -   Request took 1133 ms
20170213 11:55:16 ERROR-  - ContentElementSpliterator - Error retrieving list of elements
HotelApiSDKException(error=HotelbedsError(code=INVALID_DATA-a11d7399-8ca7-4e3d-b917-5d5c0651235e, message=Invalid data. Invalid format for date ''. Date format is yyyy-MM-dd or yyyy-MM-ddTHH:mm:ss.SSS))
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteContentAPI(HotelApiClient.java:756)
	at com.hotelbeds.distribution.hotel_api_sdk.ContentElementSpliterator.getElementBlock(ContentElementSpliterator.java:86)
	at com.hotelbeds.distribution.hotel_api_sdk.ContentElementSpliterator.<init>(ContentElementSpliterator.java:70)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.getAllElements(HotelApiClient.java:615)

It seems like the parameter lastUpdateTime was not set correctly.
I will got same error when get all hotels. I think it is the same reason. So how can I set the parameter like lastUpdateTime, countryCodes, .etc?
How can I prevent this error?

**Comment by Zavierazo** [comment]
Hi @chriszhangz, solved with version 0.12-SNAPSHOT

<dependency>
  <groupId>com.hotelbeds.hotel-api-sdk-java</groupId>
  <artifactId>hotel-api-sdk</artifactId>
  <version>0.12-SNAPSHOT</version>
</dependency>

**Comment by chriszhangz** [comment]
@Zavierazo Thanks bro it's finally working.
