### ISSUE TITLE
JsonMappingException: Can not instantiate value of type [simple type, class java.time.LocalDate] from String value ('2017-03-22');

### ISSUE THREAD

**Issue by nemnesic** [hotelbeds-sdk/hotel-api-sdk-java#24]
I tried running a simple search using your example from the demo but I got the following error during parsing of the response:
```HotelApiSDKException(error=HotelbedsError(code=Invalid response, message=Wrong content typetext/xml))

com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient Error parsing JSON response:
 com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class java.time.LocalDate] from String value ('2017-03-22'); no single-String constructor/factory method
 at [Source: java.io.StringReader@220aafde; line: 1, column: 260864] (through reference chain: com.hotelbeds.hotelapimodel.auto.messages.AvailabilityRS["hotels"]->com.hotelbeds.hotelapimodel.auto.model.Hotels["checkIn"])
```

**Comment by vmavromatis** [comment]
Hello @nemnesic, apologies for the late response. I assume you are using the RequestingAvailability demo? If that is the case, have you altered the date variables? In the demo these are used:
```
LocalDate checkIn = LocalDate.now().plusMonths(1);
LocalDate checkOut = LocalDate.now().plusMonths(1).plusDays(3);
```
But you can manually enter yours as following:
```
LocalDate checkIn = LocalDate.parse("2018-03-13");
LocalDate checkOut = LocalDate.parse("2018-03-14");
```

I hope this helps. Please provide more info regarding your code alterations, if you are still getting an error.

**Comment by Verdoso** [comment]
That looks like an issue with the Jackson library and the new Java 8 date types.
The Java SDK includes the extra handlers for the Java 8 date types:
`    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr310</artifactId>
      <version>2.6.3</version>
    </dependency>
`
But it looks as it is not correctly registered, because it should handle the new types automagically.
Can you verify that .jar file is in the classpath when you are running the SDK?

**Comment by nemnesic** [comment]
Yea java sdk had many other issues so I ended up building my own version. Are you officially supporting this? If yes, is it 6 month response time normal?

**Comment by nemnesic** [comment]
Oh that makes sense. They should remove it from their official docs then. Thank you for your response. I'll send my feedback to HBS crew.

**Comment by vmavromatis** [comment]
Hello @nemnesic, from now we will be supporting our SDKs more and try to provide help and resolve any issues in a timely manner. This is also the reason that I am going through all the old issues these days. Also expect more updates and improvements in documentation.

Please feel free to open any issue regarding the Java SDK.

**Comment by vmavromatis** [comment]
Hello @nemnesic, we will be supporting our SDKs even more and will be providing help and resolving any issues in a timely manner. This is also the reason that I am going through all the old issues these days. Also expect more updates and improvements in documentation.

Edit: To answer to your query, the SDKs are fully supported by Hotelbeds. I am considering this issue as resolved, please feel free to re-open if there are any more problems with the Jackson library.
