### ISSUE TITLE
Version number is not updated in SDK

### ISSUE THREAD

**Issue by echozbb** [hotelbeds-sdk/hotel-api-sdk-java#29]
Hi Support, I got the email which suggest us to use new endpoint https://api.hotelbeds.com/hotel-api/1.2/bookings for bookings, while seems SKD HotelApiVersion class is not updated to support 1.2

How can I call the new endpoint by SDK?

**Comment by vmavromatis** [comment]
Hi @echozbb, apologies for the late response.

Right now, you can change it manually in types/HotelApiVersion. When we update the SDK, we will add the newer API versions. 

I hope this helps.

**Comment by devel04** [comment]
Hi, is version 1.2 supported in any latest release? Doesn't seem to be available in 0.15.
Is there any other way to get endpoint version to 1.2?

Many thanks

Regards

Nicola
