### ISSUE TITLE
Java 1.7

### ISSUE THREAD

**Issue by parischung** [hotelbeds-sdk/hotel-api-sdk-java#3]
Hotelbeds Java SDK uses Java 1.8. 
Is Java SDK for Java 1.7 available?

**Comment by Verdoso** [comment]
Right now, there is no SDK version compatible with Java 7. Most of the code would be easily portable as the models are basically POJOs and there are just a couple of places where Java 8 structures are being used.

**Comment by Verdoso** [comment]
Having a look at it, most of the issues could be solved by replacing java.time with an alternative, and removing stream support from the HotelApiClient
