### ISSUE TITLE
ContentType.FACILITY_TYPE have wrong request and response class properties

### ISSUE THREAD

**Issue by tpenakov** [hotelbeds-sdk/hotel-api-sdk-java#31]
This is how the 
com.hotelbeds.distribution.hotel_api_sdk.types.ContentType.FACILITY_TYPE is created:

`FACILITY_TYPE("facilitytypologies", HotelContentPaths.TYPES_URL, FacilitiesRQ.class, FacilitiesRS.class, ContentType.FunctionHolder.FACILITY_TYPE_EXTRACTOR, new String[0]),`

Request class should be: com.hotelbeds.hotelcontentapi.auto.messages.FacilityTypesRQ
and response class should be: com.hotelbeds.hotelcontentapi.auto.messages.FacilityTypologiesRS 

PS. There is not a problem request class to stay in that way because it is irrelevant, but the response class should be changed accordingly

**Comment by vmavromatis** [comment]
Hi @tpenakov, yes this should be an easy change.

Can you please show me how you iterate through FacilityType elements? (so I can fully replicate)
Something similar to:
```java
for (FacilityType element : apiClient.getAllFacilityTypes("ENG", false)) {
    log.debug("FacilityType: {} - {}", new Object[] {
            element.getCode()
    });
}
```

**Comment by tpenakov** [comment]
Hi @vmavromatis,

`List<FacilityType> result = getHotelApiClient().getAllFacilityTypes(DEFAULT_LANGUAGE, true);`

You will see that the result list is empty.
I've also tried and:

`                List<FacilityType> result = getHotelApiClient()
                        .facilityTypesStream(DEFAULT_LANGUAGE, true)
                        .collect(Collectors.toList());
`

This might help you - the debugger shows me that the results are correctly retrieved as string from the rest service, but the ObjectMapper is unable to deserialize them because the expected type is FacilitiesRS, but should be FacilityTypologiesRS.

IMO you need to change only this enum value to become:
`FACILITY_TYPE("facilitytypologies", HotelContentPaths.TYPES_URL, FacilityTypesRQ.class, FacilityTypologiesRS.class, ContentType.FunctionHolder.FACILITY_TYPE_EXTRACTOR, new String[0])`

**Comment by vmavromatis** [comment]
As of the latest release I consider this issue resolved therefore closing this ticket. Please feel free let me know if you need anything else.
Regards
