### ISSUE TITLE
Hotelbeds Modification

### ISSUE THREAD

**Issue by RaquelViajesElCorteIngles** [hotelbeds-sdk/hotel-api-sdk-java#35]
I use 0.13-SNAPSHOT SDK´s version and the object BookingChangeRQ doesn´t work.

I need the latest version where this object is working. 
Thanks you.

**Comment by vmavromatis** [comment]
Hello @RaquelViajesElCorteIngles, the latest version of the SDK is here https://github.com/hotelbeds-sdk/hotel-api-sdk-java/tree/feature/contentType. I will test out the BookingChangeRQ class and let you know ASAP. If it works fine, I will add it to the demo too.

Please feel free to try it out yourself as well and let me know if it works for you. I hope this helps.

**Comment by RaquelViajesElCorteIngles** [comment]
Hello @vmavromatis have you got new information about that? Thanks you

**Comment by vmavromatis** [comment]
Hi @RaquelViajesElCorteIngles, I have had another look - the model/fields exist but the method in the main class and Paths has not been developed yet. We will be including this with the 0.14 release of the SDK.

I will be posting any updates in this thread.

**Comment by vmavromatis** [comment]
Hi @RaquelViajesElCorteIngles  as of now this should be implemented. Can you please try the latest SDK release with:

<dependency>
      <groupId>com.hotelbeds.hotel-api-sdk-java</groupId>
      <artifactId>hotel-api-sdk</artifactId>
      <version>0.14-SNAPSHOT</version>
</dependency>
and let me know if it works for you? (I included a bookingchange example in the demo)

Regards

**Comment by vmavromatis** [comment]
I consider this issue resolved. Please feel free let me know if you need anything else. 
Regards
