### ISSUE TITLE
Unable to set version = 1.2 in the SDK

### ISSUE THREAD

**Issue by mark-anzcro** [hotelbeds-sdk/hotel-api-sdk-java#57]
Hi Team,

I’m going over the final notes for certification, and we have the following problem which looks like it is preventing us from completing certification against the live environment.

In your note, you ask:

PLEASE NOTE THAT: In confirmation step (BookingRQ) please change version 1.0 to 1.2

https://api.hotelbeds.com/hotel-api/1.2/{operation} **ONLY IN CONFIRMATION STEP**

Our version of the SDK does not seem to support version 1.2, and looking at your GitHub repo, the current latest version 0.15-SNAPSHOT does not either:

https://github.com/hotelbeds-sdk/hotel-api-sdk-java/blob/master/hotel-api-sdk/src/main/java/com/hotelbeds/distribution/hotel_api_sdk/types/HotelApiVersion.java

When we instantiate the client we are using the following constructor:

HotelApiClient client = new HotelApiClient(config.getEnvironment(),
                                           config.getApiKey(),
                                           config.getSharedSecret());
I see there is a version of that constructor that allows us to specify a version, but the only valid versions are `DEFAULT` and `V1`.

Can you please advise how to set the version to 1.2 via the SDK without having to maintain a separate version of it?

**Comment by BrodriguezHbeds** [comment]
Hi @mark-anzcro,

Do not worry, we updated our API specification to support both 1.0 and 1.2 in the booking step (the 1.2 was a differentiation made in regards to the payment method), so is ok to use 1.0 as version.

In fact we deleted all referenes to the 1.2 version in our developer portal: https://developer.hotelbeds.com/docs/read/Hotel_Endpoints_and_Headers

Thanks and regards

**Comment by mark-anzcro** [comment]
Thanks, closing this issue.  I'll also make sure our account manager and the certification team are aware of this.
