### ISSUE TITLE
Maven not able to download sdk from repo

### ISSUE THREAD

**Issue by aangelog** [hotelbeds-sdk/hotel-api-sdk-java#61]
Hi,

I am not able to download the sdk jar from the repository posted. I am using the notes here: https://github.com/hotelbeds-sdk/hotel-api-sdk-java

and adding both the repo noted and the dependency on my pom file.

Intelij won't download it and also mvn compile fails with:

[ERROR] Failed to execute goal on project travellers: Could not resolve dependencies for project com.wearetravellers:travellers:jar:1.0-SNAPSHOT: Could not find artifact com.hotelbeds.hotel-api-sdk-java:hotel-api-sdk:jar:0.15-SNAPSHOT in ossrh (https://oss.sonatype.org/content/groups/staging)

Is the README updated? Has anything changed?

Best,
Aris

**Comment by Verdoso** [comment]
Based on Nexus results: https://oss.sonatype.org/#nexus-search;quick~hotel-api-sdk

The file is there and Maven should be able to find it.

In fact, I just added it to a new test project and Maven found it and Eclipsed added it to the "Maven dependencies" list:
![sdk](https://user-images.githubusercontent.com/5923466/78769856-23227880-798e-11ea-9f5c-aaf2503ed899.PNG)

It might be a temporary problem with Nexus, or maven connectivity to the Sonatype repo.
Good luck.

PD: Not official support, just a developer ;)

**Comment by aangelog** [comment]
Well the issue was that this was not contained here:
        <repositories>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/groups/staging</url>
		</repository>
	</repositories>

as stated at the README but here:
https://oss.sonatype.org/content/repositories/snapshots

The nexus results that you copied state that but it took me some time to figure out :)

This means that the README is not correct maybe the developers should consider fixing it.

Thanks for your help!

**Comment by Verdoso** [comment]
It's weird because I copy/pasted the information from the README. My pom.xml reads...

`    
    <repositories>
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/groups/staging</url>
        </repository>
    </repositories>
`
And it worked for me.
Cheers!
